version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/backend
    env_file:
      - .env
    depends_on:
      - qdrant
      - ollama

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      # Use IPv4 address to prevent localhost resolving to IPv6 (::1)
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=nous-hermes2:Q4_K_M
    volumes:
      - ollama_data:/root/.ollama

volumes:
  qdrant_data:
  ollama_data:
